### ISSUE TITLE
Error importing pyEX (NotImplementedError: a tzinfo subclass must implement utcoffset())

### ISSUE THREAD

**Issue by iamloved** [timkpaine/pyEX#103]
I am trying to import pyEX, after having installed it through pip install pyEX.
I am using spyder 4.1.1. With python 3.8.2. In a conda environment.

When I try to import pyEX I get the following traceback error:

>  import pyEX
> Traceback (most recent call last):
>   File "<ipython-input-13-2e53619a2b12>", line 1, in <module>
>     import pyEX
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/pyEX/__init__.py", line 2, in <module>
>     from .client import *  # noqa: F401, F403
> 
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/pyEX/client.py", line 5, in <module>
>     from .alternative import crypto, cryptoDF, \
> 
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/pyEX/alternative/__init__.py", line 1, in <module>
>     from .alternative import crypto, cryptoDF, sentiment, sentimentDF, ceoCompensation, ceoCompensationDF  # noqa: F401
> 
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/pyEX/alternative/alternative.py", line 91, in <module>
>     def ceoCompensation(symbol, token='', version='', filter=''):
> 
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/pyEX/common.py", line 310, in _wrapper
>     return expire(**temporal_args)(foo)
> 
>   File "/home/sol/miniconda3/envs/python3/lib/python3.8/site-packages/temporalcache/expire.py", line 54, in _wrapper
>     last = datetime.datetime.now(tz=tz)
> 
> NotImplementedError: a tzinfo subclass must implement utcoffset()

Why?

**Comment by timkpaine** [comment]
@iamloved can you try upgrading `pytz`

**Comment by iamloved** [comment]
Thanks for responding.
Yes. This conda environment is a fresh install. Everything is new. 
The version of pytz is 2019.3. Pip tells me I have the most recent. I tried removing pytz now and reinstalling it. But still the same error.

**Comment by lbottan** [comment]
I have the same issue. any help?

**Comment by lbottan** [comment]
same issue also in pycharm

in expire.py:
    def _wrapper(foo):
        last = datetime.datetime.now(tz=tz)

(<class 'NotImplementedError'>, NotImplementedError('a tzinfo subclass must implement utcoffset()'), <traceback object at 0x00000289BB65A308>)

**Comment by timkpaine** [comment]
can you try updating to 0.2.1

**Comment by iamloved** [comment]
OK.
Updated now. Tried again. But unfortunately I get the same error again..

**Comment by iamloved** [comment]
AHA! Thanks!! 
Working nicely now :)
